<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>estefania_pkg</name>
  <version>0.0.0</version>
  <description>Publisher and subscriber for the Estefania onboarding task.</description>
  <maintainer email="e.correa-mendez@wsu.edu">Estefania Correa-Mendez</maintainer>
  <license>MIT</license>

  <depend>onboarding_msgs</depend>
  <depend>rclcpp</depend>
  <depend>std_msgs</depend>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <test_depend>ament_lint_auto</test_depend>
  <test_depend>ament_lint_common</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>